### PR TITLE
Compile time validation and semantic naming of annotations

### PR DESCRIPTION
**Pull request by georgiosd**
Notes:

I understand the deprecation is a big change to your API so I won't be offended if you just fix the bug in NotEmpty. I was always getting confused as to what each annotation did so I changed the names to match the BCL.

Changelog:

Added compile time validation of the param/return val types that contracts are applied to. This fixes a bug in NotEmpty which only checked for empty collection but allowed tests to pass for string also.

Deprecated NotEmpty and NotBlank contracts and replaced them with attributes that have names that are more semantically correct and consistent with the .NET BCL

### CODE REVIEW

**Comment by Pathoschild** [comment]
Hi Georgios. Thanks for the contribution!

I merged in your compile-time validation with a few changes. I moved the validation into a new `IValidateContractUsageAttribute` (implemented by `[RequiresReferenceType]` and `[RequiresType(types)]`), which I think makes the code a bit easier to follow and extend. I also reduced the validation severity a bit — an incorrectly-used annotation will raise a warning and be ignored, instead of raising an error.

I also merged in your `[NotNullOrEmpty]`/`[NotNullOrWhitespace]` attributes (which actually existed until 2c487bdc9abc58a167334efc30a51b9170660642), but I renamed `[NotNullOrWhitespace]` to match the existing `[NotBlank]` annotation.

I didn't deprecate `[NotEmpty]`/`[NotBlank]` because their semantics aren't equivalent to the new `[NotNullOr*]` methods. They specifically guard against empty/blank values, but not `null` values. This is useful for handling optional parameters:

``` c#
void SomeMethod([NotBlank] string someKey = null) {
   someKey = someKey ?? this.GenerateKey();
}
```

I'll update the NuGet package in a few days once I've tested the release in a few projects to make sure there are no new issues. Thanks again!

**Comment by georgiosd** [comment]
That's great! 

Can you please see if you can get the nuget working with both 2.1 and 3.0 of P#? I couldn't get the current nuget to compile against the 3.0 nuget (but seems to work ok with 3.0 installed on the machine and the 2.1 nuget)

**Comment by Pathoschild** [comment]
@georgiosd: I'm looking into the PostSharp 3 support and created a separate ticket for that (#5).

**Comment by Pathoschild** [comment]
These changes are in the [1.1.0 NuGet package](https://nuget.org/packages/Pathoschild.DesignByContract/1.1.0).

**Pull request merged**
